---
- name: Deploy Node.js Application on Nginx
  hosts: webserver
  become: yes
  tasks:
    - name: Install Docker if not already installed
      apt:
        name: docker.io
        state: present
        

    - name: Ensure Nginx is installed
      apt:
        name: nginx
        state: present
        

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Configure Nginx to proxy requests
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
      notify:
        - Restart Nginx

    - name: Pull Node.js Docker image
      docker_image:
        name: prashantritgit/nodejs:latest 
        pull: yes

    - name: Run Node.js Docker container
      docker_container:
        name: nodejscon
        image: prashantritgit/nodejs:latest
        state: started
        published_ports:
          - "3000:3000"  

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted

