apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  labels:
    app: nginx
spec:
  selector:
    app: nginx  # Matches the label in the deployment
  ports:
    - protocol: TCP
      port: 80            # The port exposed by the service
      targetPort: 80      # The port exposed by the nginx container
  type: NodePort
